# Makefile

BINARIES=boom16_c boom16_r boom15_c boom15_r boom14_c boom14_r boom13_c boom13_r boom12_c boom12_r \
boom11_c boom11_r boom10_c boom10_r boom9_c boom9_r boom8_c boom8_r boom7_c boom7_r boom6_c boom6_r \
boom5_c boom5_r boom4_c boom4_r boom3_c boom3_r boom2_c boom2_r

all : $(BINARIES)
	@echo "done -------------"
	@ls -l

boom16_c : boom16_c.c
	-time gcc -O2 boom16_c.c -o boom16_c

boom16_c.c : boom16.mtc
	-time mtcc -c boom16.mtc boom16_c.c
	-rm -f *.PmT

boom16_r : boom16_r.c
	-time gcc -O2 boom16_r.c -o boom16_r

boom16_r.c : boom16.mtc
	-time mtcc -e boom16.mtc boom16_r.c
	-rm -f *.PmT

boom15_c : boom15_c.c
	-time gcc -O2 boom15_c.c -o boom15_c

boom15_c.c : boom15.mtc
	-time mtcc -c boom15.mtc boom15_c.c
	-rm -f *.PmT

boom15_r : boom15_r.c
	-time gcc -O2 boom15_r.c -o boom15_r

boom15_r.c : boom15.mtc
	-time mtcc -e boom15.mtc boom15_r.c
	-rm -f *.PmT

boom14_c : boom14_c.c
	-time gcc -O2 boom14_c.c -o boom14_c

boom14_c.c : boom14.mtc
	-time mtcc -c boom14.mtc boom14_c.c
	-rm -f *.PmT

boom14_r : boom14_r.c
	-time gcc -O2 boom14_r.c -o boom14_r

boom14_r.c : boom14.mtc
	-time mtcc -e boom14.mtc boom14_r.c
	-rm -f *.PmT

boom13_c : boom13_c.c
	-time gcc -O2 boom13_c.c -o boom13_c

boom13_c.c : boom13.mtc
	-time mtcc -c boom13.mtc boom13_c.c
	-rm -f *.PmT

boom13_r : boom13_r.c
	-time gcc -O2 boom13_r.c -o boom13_r

boom13_r.c : boom13.mtc
	-time mtcc -e boom13.mtc boom13_r.c
	-rm -f *.PmT

boom12_c : boom12_c.c
	-time gcc -O2 boom12_c.c -o boom12_c

boom12_c.c : boom12.mtc
	-time mtcc -c boom12.mtc boom12_c.c
	-rm -f *.PmT

boom12_r : boom12_r.c
	-time gcc -O2 boom12_r.c -o boom12_r

boom12_r.c : boom12.mtc
	-time mtcc -e boom12.mtc boom12_r.c
	-rm -f *.PmT

boom11_c : boom11_c.c
	-time gcc -O2 boom11_c.c -o boom11_c

boom11_c.c : boom11.mtc
	-time mtcc -c boom11.mtc boom11_c.c
	-rm -f *.PmT

boom11_r : boom11_r.c
	-time gcc -O2 boom11_r.c -o boom11_r

boom11_r.c : boom11.mtc
	-time mtcc -e boom11.mtc boom11_r.c
	-rm -f *.PmT

boom10_c : boom10_c.c
	-time gcc -O2 boom10_c.c -o boom10_c

boom10_c.c : boom10.mtc
	-time mtcc -c boom10.mtc boom10_c.c
	-rm -f *.PmT

boom10_r : boom10_r.c
	-time gcc -O2 boom10_r.c -o boom10_r

boom10_r.c : boom10.mtc
	-time mtcc -e boom10.mtc boom10_r.c
	-rm -f *.PmT

boom9_c : boom9_c.c
	-time gcc -O2 boom9_c.c -o boom9_c

boom9_c.c : boom9.mtc
	-time mtcc -c boom9.mtc boom9_c.c
	-rm -f *.PmT

boom9_r : boom9_r.c
	-time gcc -O2 boom9_r.c -o boom9_r

boom9_r.c : boom9.mtc
	-time mtcc -e boom9.mtc boom9_r.c
	-rm -f *.PmT

boom8_c : boom8_c.c
	-time gcc -O2 boom8_c.c -o boom8_c

boom8_c.c : boom8.mtc
	-time mtcc -c boom8.mtc boom8_c.c
	-rm -f *.PmT

boom8_r : boom8_r.c
	-time gcc -O2 boom8_r.c -o boom8_r

boom8_r.c : boom8.mtc
	-time mtcc -e boom8.mtc boom8_r.c
	-rm -f *.PmT

boom7_c : boom7_c.c
	-time gcc -O2 boom7_c.c -o boom7_c

boom7_c.c : boom7.mtc
	-time mtcc -c boom7.mtc boom7_c.c
	-rm -f *.PmT

boom7_r : boom7_r.c
	-time gcc -O2 boom7_r.c -o boom7_r

boom7_r.c : boom7.mtc
	-time mtcc -e boom7.mtc boom7_r.c
	-rm -f *.PmT

boom6_c : boom6_c.c
	-time gcc -O2 boom6_c.c -o boom6_c

boom6_c.c : boom6.mtc
	-time mtcc -c boom6.mtc boom6_c.c
	-rm -f *.PmT

boom6_r : boom6_r.c
	-time gcc -O2 boom6_r.c -o boom6_r

boom6_r.c : boom6.mtc
	-time mtcc -e boom6.mtc boom6_r.c
	-rm -f *.PmT

boom5_c : boom5_c.c
	-time gcc -O2 boom5_c.c -o boom5_c

boom5_c.c : boom5.mtc
	-time mtcc -c boom5.mtc boom5_c.c
	-rm -f *.PmT

boom5_r : boom5_r.c
	-time gcc -O2 boom5_r.c -o boom5_r

boom5_r.c : boom5.mtc
	-time mtcc -e boom5.mtc boom5_r.c
	-rm -f *.PmT

boom4_c : boom4_c.c
	-time gcc -O2 boom4_c.c -o boom4_c

boom4_c.c : boom4.mtc
	-time mtcc -c boom4.mtc boom4_c.c
	-rm -f *.PmT

boom4_r : boom4_r.c
	-time gcc -O2 boom4_r.c -o boom4_r

boom4_r.c : boom4.mtc
	-time mtcc -e boom4.mtc boom4_r.c
	-rm -f *.PmT

boom3_c : boom3_c.c
	-time gcc -O2 boom3_c.c -o boom3_c

boom3_c.c : boom3.mtc
	-time mtcc -c boom3.mtc boom3_c.c
	-rm -f *.PmT

boom3_r : boom3_r.c
	-time gcc -O2 boom3_r.c -o boom3_r

boom3_r.c : boom3.mtc
	-time mtcc -e boom3.mtc boom3_r.c
	-rm -f *.PmT

boom2_c : boom2_c.c
	-time gcc -O2 boom2_c.c -o boom2_c

boom2_c.c : boom2.mtc
	-time mtcc -c boom2.mtc boom2_c.c
	-rm -f *.PmT

boom2_r : boom2_r.c
	-time gcc -O2 boom2_r.c -o boom2_r

boom2_r.c : boom2.mtc
	-time mtcc -e boom2.mtc boom2_r.c
	-rm -f *.PmT

clean :
	rm -f $(BINARIES) *.c *.PmT *.log
